import math
print(math.sqrt(64))
print(math.ceil(8.54))
print(math.pow(3,2))
print(math.factorial(5))
print(math.floor(5.65))
print(math.fmod(20,5))
a,b=divmod(10,2)
print(a,b)
n=int(input())
x=math.factorial(n)
print("the factorial of {} is {}".format(n,x))
